void cliente();
void servidor();
int atualizaMem(int arg1, int arg2, int arg3);
int atualizaCpu(int arg1, int arg2, int arg3);
int convAlocCpu(char *arg1);
int convAlocMem(char *arg1);
int convAlocTempo(char *arg1);
void respostaConsulta(char *arg1, int arg2, int arg3);
int randomizaTempo();
int randomizaCpu();
int randomizaMemoria();
void constMsgCliente(char *arg1,int arg2,int arg3);
