void cliente();
void servidor();
int calculaCapacidadeMemoria(int arg1, int arg2);
int calculaCapacidadeCPU(int arg1,int arg2);
int mantemRequisicao(int arg);
int socket(int arg);
int salvaCapacidadeRequisicao(int arg);
int randomizaTempo();
int randomizaCpuMemoria();
char converteIntString(int arg);
void converteStringInt(char arg1[]);
